/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cclnnisoatzawqjhkofg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjbG5uaXNvYXR6YXdxamhrb2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjk5NzcsImV4cCI6MjA3NDc0NTk3N30.3VoxitVI5uX9f5kJY8TuVFl1Z4Trqz57s-XXrlc_R-8"